format_options:
  pdf:
    backend: langchain_pdf
    chunker: recursive
  docx:
    pipeline_options: simple
    backend: msword
  hwpx:
    pipeline_options: simple
    backend: hwpx
  pptx:
    backend: langchain_pptx
    chunker: recursive
  md:
    backend: langchain_md
    chunker: recursive
  csv:
    backend: tabular
  xlsx:
    backend: tabular

chunker:
  name: hybrid
  tokenizer: char
  # miniLM | char
  max_tokens: 1024

genos_url: genos.genon.ai
resource_path: /app/resource
return_level: vector
log_level: 4
